/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.augustcellars.cose.cose.java)
    api(libs.org.bouncycastle.bcpkix.jdk18on)
    api(libs.org.apache.santuario.xmlsec)
    api(libs.org.jdom.jdom2)
    api(libs.com.google.code.gson.gson)

    // Add Jackson libraries correctly (without parentheses)
    implementation("com.fasterxml.jackson.core:jackson-databind:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-core:2.15.2")
    implementation("com.fasterxml.jackson.core:jackson-annotations:2.15.2")

    // To canonicalize in JCS schema JSON
    implementation(files("libs/java-json-canonicalization-1.1.jar"))

}

group = "com.telefonica.api"
version = "0.0.1-SNAPSHOT"
description = "provenance-api"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}


