/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.augustcellars.cose.cose.java)
    api(libs.org.bouncycastle.bcpkix.jdk18on)
    api(libs.org.apache.santuario.xmlsec)
    api(libs.org.jdom.jdom2)
    api(libs.com.google.code.gson.gson)
}

group = "com.telefonica.api"
version = "0.0.1-SNAPSHOT"
description = "provenance-api"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.register<JavaExec>("runExample") {
    mainClass.set("com.telefonica.cose.provenance.example.Signer")
    classpath = sourceSets.main.get().runtimeClasspath
    args = listOf("ietf-interfaces.xml")
}